### ISSUE TITLE
Problem with sending data to ESP8266

### ISSUE THREAD

**Issue by animavitis** [mhaack/mqtt-433mhz-gateway-homie#1]
Hi,

I have very stupid problem and want to for help.
Can u send me what need  to be send to ESP to trigger rfSwitchNode  (TOPIC & MESSAGE from MQTT to trigger RF emiter on ESP8266)?

thx for help:)

**Comment by mhaack** [comment]
I added some sample to the readme.

```
# send RF command via MQTT & response
homie/mqtt-gateway-livingroom/MQTTto433/on/set 1394001
homie/mqtt-gateway-livingroom/MQTTto433/on 1394001
```
First line: MQTT command send from MQTT client or smart home solution. Translates into the code send by the RF transmitter.
Second line: Response from device after RF signal was send.

For a detailed documentation of the MQTT topics and commands used see [Homie documentation](https://homie-esp8266.readme.io/docs).
