### ISSUE TITLE
Read out data from remotesensor?

### ISSUE THREAD

**Issue by joe63** [mhaack/mqtt-433mhz-gateway-homie#2]
Hi,

do you think it would be possile to read out data from a 433MHz remotesensor ?
![remotesensor](https://user-images.githubusercontent.com/6555368/41188106-4f4f91f4-6ba8-11e8-8c43-4e586228cfe3.jpg)
and send the data via MQTT?

can you post your code?

thx

BR Joe

**Comment by mhaack** [comment]
Post my code? My code is in this repo.

For your temp sensor I recommend searching https://www.hackster.io, might be a good place to find such projects.
